name: Export Notebooks
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/cache@v1
      - uses: actions/cache@v3
        with:
          path: notebooks-cache
          key:          ${{ runner.os }}-${{ hashFiles('.github/workflows/ExportNotebooks.yaml') }}-${{ hashFiles('notebooks/**/*.jl') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/workflows/ExportNotebooks.yaml') }}
      - run: |
          julia --thread=auto ExportNotebooks.jl
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
